[package]
name = "bookmark"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5"
clap = {version="3.2.17", features=["derive"]}
inquire = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"